Lin_Tiffany_HW5_V2/Models/Order.cs
using System.ComponentModel.DataAnnotations;
using Lin_Tiffany_HW5_V2.Models;

namespace Lin_Tiffany_HW5_V2.Models
{
    public class Order
    {
        private const Decimal TAX_RATE = 0.0825m;

        public Int32 OrderID { get; set; }

        [Display(Name = "Order Number")]
        public Int32 OrderNumber { get; set; }

        [Display(Name = "Order Date")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime OrderDate { get; set; }

        [Display(Name = "Order Notes")]
        public String OrderNotes { get; set; }

        [Display(Name = "Order Subtotal")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Decimal OrderSubtotal
        {
            get { return OrderDetails.Sum(od => od.ExtendedPrice); }
        }

        [Display(Name = "Order Tax")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Decimal OrderTax
        {
            get { return OrderSubtotal * TAX_RATE; }
        }

        [Display(Name = "Order Total")]
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Decimal OrderTotal
        {
            get { return OrderSubtotal + OrderTax; }
        }

        public Order()
        {
            if (OrderDetails == null)
            {
                OrderDetails = new List<OrderDetail>();
            }
        }

        //ADD NAVIGATIONAL PROPERTIES

        // each order can have many order details 
        public List<OrderDetail> OrderDetails { get; set; }

        // each order can only have one user (customer) 
        public AppUser User { get; set; }

    }
}

Lin_Tiffany_HW5_V2/Controllers/OrderDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lin_Tiffany_HW5_V2.DAL;
using Lin_Tiffany_HW5_V2.Models;

namespace Lin_Tiffany_HW5_V2.Controllers
{
    public class OrderDetailsController : Controller
    {
        private readonly AppDbContext _context;

        public OrderDetailsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: OrderDetails
        public IActionResult Index(int? orderID)
        {
            if (orderID == null)
            {
                return View("Error", new String[] { "Please specify a order to view!" });
            }

            //limit the list to only the registration details that belong to this registration
            List<OrderDetail> ods = _context.OrderDetails
                                          .Include(rd => rd.Product)
                                          .Where(rd => rd.Order.OrderID == orderID)
                                          .ToList();

            return View(ods);
        }

        // GET: OrderDetails/Create
        public IActionResult Create(int orderID)
        {
            //create a new instance of the RegistrationDetail class
            OrderDetail od = new OrderDetail();

            //find the registration that should be associated with this registration
            Order dbOrder = _context.Orders.Find(orderID);

            //set the new registration detail's registration equal to the registration you just found
            od.Order = dbOrder;

            //populate the ViewBag with a list of existing courses
            ViewBag.AllProducts = GetAllProducts();

            //pass the newly created registration detail to the view
            return View(od);
        }

        // POST: OrderDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(OrderDetail orderDetail, int SelectedProduct)
        {

            //if user has not entered all fields, send them back to try again
            if (SelectedProduct == null || orderDetail.Quantity == null)
            {
                ViewBag.AllProducts = GetAllProducts();
                return View(orderDetail);
            }

            //find the course to be associated with this order
            Product dbProduct = _context.Products.Find(SelectedProduct);

            //set the registration detail's course to be equal to the one we just found
            orderDetail.Product = dbProduct;

            //find the registration on the database that has the correct registration id
            //unfortunately, the HTTP request will not contain the entire registration object, 
            //just the registration id, so we have to find the actual object in the database
            Order dbOrder = _context.Orders.Find(orderDetail.Order.OrderID);

            //set the registration on the registration detail equal to the registration that we just found
            orderDetail.Order = dbOrder;

            //set the registration detail's price equal to the course price
            //this will allow us to to store the price that the user paid
            orderDetail.ProductPrice = dbProduct.Price;

            //calculate the extended price for the registration detail
            orderDetail.ExtendedPrice = orderDetail.Quantity * orderDetail.ProductPrice;

            //add the registration detail to the database
            _context.Add(orderDetail);
            await _context.SaveChangesAsync();

            //send the user to the details page for this registration
            return RedirectToAction("Details", "Orders", new { id = orderDetail.Order.OrderID });
        }

        // GET: OrderDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return View("Error", new String[] { "Please specify a order detail to edit!" });
            }

            //find the registration detail
            OrderDetail orderDetail = await _context.OrderDetails
                                    .Include(rd => rd.Product)
                                    .Include(rd => rd.Order)
                                    .FirstOrDefaultAsync(rd => rd.OrderDetailID == id);
            if (orderDetail == null)
            {
                return View("Error", new String[] { "This order detail was not found" });
            }
            return View(orderDetail);
        }

        // POST: OrderDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, OrderDetail orderDetail)
        {
            //this is a security check to make sure they are editing the correct record
            if (id != orderDetail.OrderDetailID)
            {
                return View("Error", new String[] { "There was a problem editing this record. Try again!" });
            }

            //create a new registration detail
            OrderDetail dbOD;

            //if code gets this far, update the record
            try
            {
                //find the existing registration detail in the database
                //include both registration and course
                dbOD = _context.OrderDetails
                      .Include(rd => rd.Product)
                      .Include(rd => rd.Order)
                      .FirstOrDefault(rd => rd.OrderDetailID == orderDetail.OrderDetailID);

                //information is not valid, try again
                if (ModelState.IsValid == false)
                {
                    return View(orderDetail);
                }

                //update the scalar properties
                dbOD.Quantity = orderDetail.Quantity;
                dbOD.ProductPrice = dbOD.Product.Price;
                dbOD.ExtendedPrice = dbOD.Quantity * dbOD.ProductPrice;

                //save changes
                _context.Update(dbOD);
                await _context.SaveChangesAsync();
            }
            catch (Exception ex)
            {
                return View("Error", new String[] { "There was a problem editing this record", ex.Message });
            }


            //if code gets this far, go back to the registration details index page
            return RedirectToAction("Details", "Orders", new { id = dbOD.Order.OrderID });
        }

        // GET: OrderDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.OrderDetail == null)
            {
                return NotFound();
            }

            var orderDetail = await _context.OrderDetail
                .FirstOrDefaultAsync(m => m.OrderDetailID == id);
            if (orderDetail == null)
            {
                return NotFound();
            }

            return View(orderDetail);
        }

        // POST: OrderDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //find the registration detail to delete
            OrderDetail orderDetail = await _context.OrderDetails
                                                   .Include(r => r.Order)
                                                   .FirstOrDefaultAsync(r => r.OrderDetailID == id);

            //delete the registration detail
            _context.OrderDetails.Remove(orderDetail);
            await _context.SaveChangesAsync();

            //return the user to the registration/details page
            return RedirectToAction("Details", "Orders", new { id = orderDetail.Order.OrderID });
        }

        private bool OrderDetailExists(int id)
        {
          return (_context.OrderDetail?.Any(e => e.OrderDetailID == id)).GetValueOrDefault();
        }

        private SelectList GetAllProducts()
        {
            //create a list for all the courses
            List<Product> allProducts = _context.Products.ToList();

            //the user MUST select a course, so you don't need a dummy option for no course

            //use the constructor on select list to create a new select list with the options
            SelectList slAllProducts = new SelectList(allProducts, nameof(Product.ProductID), nameof(Product.Name));

            return slAllProducts;
        }


    }
}

Lin_Tiffany_HW5_V2/Views/Orders/Create.cshtml
@model Lin_Tiffany_HW5_V2.Models.Order

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OrderNumber" class="control-label"></label>
                <input asp-for="OrderNumber" class="form-control" />
                <span asp-validation-for="OrderNumber" class="text-danger"></span>
            </div>*@
            @*<div class="form-group">
                <label asp-for="OrderDate" class="control-label"></label>
                <input asp-for="OrderDate" class="form-control" />
                <span asp-validation-for="OrderDate" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="OrderNotes" class="control-label"></label>
                <input asp-for="OrderNotes" class="form-control" />
                <span asp-validation-for="OrderNotes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


Lin_Tiffany_HW5_V2/Views/Orders/Details.cshtml
@model Lin_Tiffany_HW5_V2.Models.Order

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Order</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.User.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrderNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrderDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.OrderNotes)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.OrderNotes)
        </dd>
    </dl>
</div>

<h5>Products on this Order</h5>
<table class="table table-primary">
    <tr>
        <th>Title</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Extended Price</th>
    </tr>

    @foreach (OrderDetail od in Model.OrderDetails)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => od.Product.Name)</td>
            <td>@Html.DisplayFor(modelItem => od.ProductPrice)</td>
            <td>@Html.DisplayFor(modelItem => od.Quantity)</td>
            <td>@Html.DisplayFor(modelItem => od.ExtendedPrice)</td>
        </tr>
    }
</table>

<h5>Order Summary</h5>
<table class="table table-sm table-bordered" style="width:30%">
    <tr>
        <th colspan="2" style="text-align:center">Order Summary</th>
    </tr>
    <tr>
        <td>Order Subtotal:</td>
        <td>@Html.DisplayFor(model => model.OrderSubtotal)</td>
    </tr>
    <tr>
        <td>Service Fee:</td>
        <td>@Html.DisplayFor(model => model.OrderTax)</td>
    </tr>
    <tr>
        <td>Registration Total:</td>
        <td>@Html.DisplayFor(model => model.OrderTotal)</td>
    </tr>
</table>

    <div>
        <a asp-action="Edit" asp-route-id="@Model?.OrderID">Edit</a> |
        <a asp-action="Index">Back to List</a>
    </div>

Lin_Tiffany_HW5_V2/Views/Orders/Edit.cshtml
@model Lin_Tiffany_HW5_V2.Models.Order

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Order</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderID" />
            @*<div class="form-group">
                    <label asp-for="OrderNumber" class="control-label"></label>
                    <input asp-for="OrderNumber" class="form-control" />
                    <span asp-validation-for="OrderNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="OrderDate" class="control-label"></label>
                    <input asp-for="OrderDate" class="form-control" />
                    <span asp-validation-for="OrderDate" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <label asp-for="OrderNotes" class="control-label"></label>
                <input asp-for="OrderNotes" class="form-control" />
                <span asp-validation-for="OrderNotes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<h5>Products on this Order</h5>
<table class="table table-primary">
    <tr>
        <th>Title</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Extended Price</th>
    </tr>

    @foreach (OrderDetail od in Model.OrderDetails)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => od.Product.Name)</td>
            <td>@Html.DisplayFor(modelItem => od.ProductPrice)</td>
            <td>@Html.DisplayFor(modelItem => od.Quantity)</td>
            <td>@Html.DisplayFor(modelItem => od.ExtendedPrice)</td>
        </tr>
    }
</table>

<div>
    <a asp-action="Index" class="btn btn-info">Back to List</a>
    <a asp-action="Create" asp-controller="OrderDetails" asp-route-orderID="@Model.OrderID" class="btn btn-warning">Add Another Item</a>
    <a asp-action="Index" asp-controller="OrderDetails" asp-route-orderID="@Model.OrderID" class="btn btn-danger">Edit Existing Items</a>
</div>


Lin_Tiffany_HW5_V2/Views/Orders/Index.cshtml
@model IEnumerable<Lin_Tiffany_HW5_V2.Models.Order>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>


@if (User.Identity.IsAuthenticated && User.IsInRole("Customer"))
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OrderNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderNotes)
            </th>
            <th>
                Order Total
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderNotes)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderTotal)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.OrderID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.OrderID">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>